#!/usr/bin/env bash
apt-get install python-pkg-resources
apt-get install libboost-regex-dev
apt-get install debhelper
apt-get install libgmp3-dev
apt-get install automake
apt-get install autoconf
apt-get install texlive
apt-get install texlive-latex-recommended
apt-get install texlive-fonts-recommended
apt-get install texlive-latex-extra
apt-get install texlive-lang-cyrillic
apt-get install texlive-lang-english
apt-get install tidy
apt-get install ghostscript
pip2 install pytest
pip2 install pyyaml
pip2 install pytest
pip2 install plastex
